### ISSUE TITLE
Urls don't open in firefox running with xwayland in sway

### ISSUE THREAD

**Issue by eternal-sorrow** [flatpak/xdg-desktop-portal#285] opened 2019-01-12 20:31 UTC
I use Telegram Desktop application as flatpak and firefox as native app. Also I use Wayland (sway) and firefox runs with Xwayland compatibility layer. When I click on some url in telegram app, it doesn't open in browser. In `systemctl --user status xdg-desktop-portal` I see a lot of lines `Error: no DISPLAY environment variable specified` (new line appears every time I click on url).

**Comment by jccr** [comment] 2019-11-03 18:45
I use vivaldi and wayland (sway). My URLs won't open either.
I'm getting something similar to:
> In systemctl --user status xdg-desktop-portal I see a lot of lines Error: no DISPLAY environment variable specified (new line appears every time I click on url).

The difference being I get this line every time I click on a URL:
`xdg-desktop-portal[18289]: (vivaldi-stable:1977486): Gtk-WARNING **: 10:42:46.564: cannot open display:`

**Comment by matthiasclasen** [comment] 2019-11-05 14:38
Does the xdg-desktop-portal process have DISPLAY set in the environment ?

What does this say?

```
strings /proc/$(pidof xdg-desktop-portal)/environ | grep DISPLAY
```

**Comment by divoxx** [comment] 2019-11-13 20:45
I'm having the same issue.

@matthiasclasen I don't see `DISPLAY` defined in my environment.

**Comment by returntrip** [comment] 2020-07-28 15:30
For the sway/wayland users, this should be sufficient to get (native) Firefox to open links from Flatpaks (tested with im.riot.Riot).

Add this `exec "dbus-update-activation-environment --systemd DISPLAY MOZ_DBUS_REMOTE"` towards the end of your sway `config` file.

Make sure to first `export MOZ_DBUS_REMOTE=1` (perhaps in `.bashrc`).

`MOZ_DBUS_REMOTE` is necessary to avoid this issue: https://github.com/swaywm/sway/wiki#i-cant-open-links-in-external-applications-in-firefox

**Comment by rrichardson** [comment] 2020-10-29 19:57
I am running Sway on SilverBlue and I, too was getting similar errors in xdg-desktop-portal: 

```
Oct 29 12:04:48 localhost.localdomain xdg-desktop-portal[4551]: Error: no DISPLAY environment variable specified
Oct 29 12:05:18 localhost.localdomain xdg-desktop-por[4515]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list
Oct 29 12:09:03 localhost.localdomain xdg-desktop-portal[5368]: Error: no DISPLAY environment variable specified
Oct 29 12:09:06 localhost.localdomain xdg-desktop-portal[5390]: Error: no DISPLAY environment variable specified
```
I did verify that every time I clicked a link in one of the flatpak apps I'd see a new `no DISPLAY... ` message. 

I followed the advice from @returntrip - and now I no longer see the error message, but I get the firefox dialog box that is mentioned in the wiki.  

So I guess that's progress!  I have verified that firefox was launched with the MOZ_DBUS_REMOTE=1 variable, so I need to find some other approach.

**Comment by hadess** [comment] 2020-10-29 23:14
The problem is that sway (or whatever else actually starts `Xwayland`) never sends the new DISPLAY environment variable to the user systemd. So when systemd activates xdg-desktop-portal, it doesn't have a DISPLAY envvar to pass to it, which means that xdg-desktop-portal can't pass it to the firefox instance that it launches.

This is how it's implemented in mutter (which makes it go through gnome-session, which feeds the user systemd):
https://gitlab.gnome.org/GNOME/mutter/blob/master/src/wayland/meta-wayland.c#L495
https://gitlab.gnome.org/GNOME/mutter/blob/master/src/wayland/meta-wayland.c#L300-336

You'll need to figure out how that needs to be implemented when using sway, and its session manager.

**Comment by hadess** [comment] 2020-10-30 10:29
I'll close this. You'll need to file a bug against sway about this problem, as even by running `dbus-update-activation-environment` by hand, you'd probably still want to make sure that the display matches what sway used when spawning the server.

Or work-around the problem by adding those lines to your sway startup script:
```
export DISPLAY=:0
dbus-update-activation-environment --systemd DISPLAY
```

**Closed by hadess** 2020-10-30 10:29 UTC

**Comment by emersion** [comment] 2020-10-30 21:30
>The problem is that sway (or whatever else actually starts Xwayland) never sends the new DISPLAY environment variable to the user systemd. 

xdg-desktop-portal shouldn't rely on this. Sway has nothing to do with systemd.

**Comment by eternal-sorrow** [comment] 2022-05-25 19:06
I'm using Firefox on Wayland now, but I'm still getting this problem sometimes. Even though I have `dbus-update-activation-environment --systemd --all` in my sway config. If I unset the DISPLAY variable in the terminal and run `xdg-open https://exampe.com`, it opens the URL in Firefox as it should. But xdg-desktop-portal fails to open it with `Error: no DISPLAY environment variable specified`.

**Comment by smcv** [comment] 2023-09-01 13:22
> > The problem is that sway (or whatever else actually starts Xwayland) never sends the new DISPLAY environment variable to the user systemd.
> 
> xdg-desktop-portal shouldn't rely on this. Sway has nothing to do with systemd.

On systems that use `systemd --user`, xdg-desktop-portal is a `systemd --user` service. If the desktop session doesn't tell `systemd --user` how to start an X11 application (`DISPLAY` and maybe other necessary environment variables like `XAUTHORITY`), then X11 applications will not be startable as a descendant of `systemd --user`; and as long as users are relying on X11 applications, that will cause user-visible broken situations. xdg-desktop-portal is not in a position to fix dependencies and system integration among components larger than itself.

I'm sure Sway itself has nothing to do with systemd, but if it's providing the implementation of X11 on a system that uses `systemd --user`, then *something* in the desktop session path - maybe Sway, maybe some "larger" component like a display manager, or maybe some "smaller" component that is responsible for Xwayland - needs to do this.

I'm sorry if the need for a desktop environment to interact with other system infrastructure offends your sense of orthogonality, but the maintainers of xdg-desktop-portal didn't design the X11 protocol and are not able to change history, and X11's reliance on environment variables is much older than xdg-desktop-portal (and probably also older than my lifetime).

See also https://github.com/swaywm/sway/issues/5777#issuecomment-802415482 which is how one particular system integrator chose to address this.

**Comment by emersion** [comment] 2023-09-01 13:32
This has nothing specific to X11, Wayland clients also need `WAYLAND_DISPLAY` to be set under Sway (the "default" value used when `WAYLAND_DISPLAY` is missing is seen as a mistake by wlroots and Weston developers, because it essentially connects to a random compositor).

Sway is not designed to be used with systemd, nor xdg-desktop-portal. Sway will not add special treatment for these. The recommended approach is to not use systemd to manage Wayland-related services.
