### ISSUE TITLE
Using wrong implementation, -gtk instead of -gnome

### ISSUE THREAD

**Issue by gegoxaren** [flatpak/xdg-desktop-portal#859] opened 2022-08-14 22:36 UTC
Hello!
This is not really a problem with the software per-se, but I need some help.

I am having a bit of a problem, I'm trying to get the screen capture desktop portal working on Ubuntu 22.04. Becouse the interface is missing in the GTK implementation, it will not show up in OBS. (But it is present in the GNOME one).

When I try to use the ASHPD Demo to call different methods, it looks like it's using the GTK portal, instead of the GNOME portal, as it attaches a modular to the parent window, instead of 

I have tried to do what others have done who has had the same problem but to no avail. 

The `xdg-desktop-portal-gnome` service does not start on login, but the GTK one does. I have to activate it manually, but it will not be show any prompt.

ASHPD Demo output for Screen Cast:
https://gist.github.com/gegoxaren/7b831766787bb3e42375e9bcb534324b

Output from `systemctl --user status xdg-desktop-portal-gtk.service` 
https://gist.github.com/gegoxaren/5e7a71c16c6317d6417a37f637211cd8

The GNOME desktop portal service seems to start normally, and the status has no indications that as to what might be wrong.

Is there some file I should change to make this work as it should? I highly suspect I might have done something odd, but I can't for the life of me figure out what it may be.

Thank you for your time,
Gustav.

**Comment by orowith2os** [comment] 2022-09-08 21:12
The GTK and GNOME portals are one and the same, as far as I know. However, if you'd like the portal to start by itself, a simple `systemctl enable` should do the trick.

I would appreciate some input from someone more experienced with the portals just to be sure.

**Comment by GeorgesStavracas** [comment] 2022-12-12 19:21
I cannot reproduce this. Can you still? Have you manually enabled xdg-desktop-portal-gtk before? Which version of xdg-desktop-portal are you using?

**Comment by Mikenux** [comment] 2023-08-29 01:53
There has been no response for a long time...

**Comment by GeorgesStavracas** [comment] 2023-08-29 12:47
Yeah, and this should be fixed with the new config-based portal matching system. Closing.

**Closed by GeorgesStavracas** 2023-08-29 12:47 UTC
Labels: bug, backend specific
