### ISSUE TITLE
Latest release breaks File Chooser and alike

### ISSUE THREAD

**Issue by vars1ty** [flatpak/xdg-desktop-portal#1131] opened 2023-10-07 18:18 UTC
The latest release (grabbed from Arch Linux's repository, latest version: `1.18.0-2`) breaks several portal implementations, such as file picker and more.

I tried to revert back to 1.16.0 (`1.16.0-3`) and it started working again.
To reproduce, spin up an install of Hyprland via archinstall and run Firefox from Flatpak, then try hitting CTRL+O to open the file picker, notice it not working.

**Comment by M1cha** [comment] 2023-10-08 09:09
I have the same issue. With `d-feet` you can see, that the `org.freedesktop.portal.Desktop` service simply doesn't expose the services provided by the GTK implementation anymore.

**Comment by zmazanv** [comment] 2023-10-09 05:29
I have the same issue on Arch with the update to `xdg-desktop-portal-1.18.0-2`. Reverting back to version `xdg-desktop-portal-1.16.0-3` corrects the issue.

I use Arch Linux with Hyprland, for which I use the `xdg-desktop-portal-hyprland` and `xdg-desktop-portal-gtk` portals to get the needed impls for `xdg-desktop-portal`. Version `1.18.0-2` breaks the GTK portal impl, causing it to not start nor be detected.

**Comment by tytan652** [comment] 2023-10-09 08:48
Source: https://github.com/flatpak/xdg-desktop-portal/releases/tag/1.18.0

> Changes that might be relevant for distributors:
> - Rework how portal implementations are loaded. This new, more robust system allows selecting specific backends for specific portals, and layering them when necessary. Platforms that provide portals implementation are encouraged to provide a suitable configuration file.

-----------------------------

This is not a bug, Arch Linux should provide a suitable configuration file inside DE package that do not actually do it.

The best would be that each DE provide one one their next version and a really basic one for wlroots compositor like sway or hyperland, users can create their own config file to override it like it is explained [here](https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals-conf.rst).

**Comment by GeorgesStavracas** [comment] 2023-10-09 16:34
Please see https://github.com/flatpak/xdg-desktop-portal/issues/1077#issuecomment-1715896552

With version 1.18, either your distribution of choice, your desktop environment, or you independently should provide a portal configuration file specifying which backends to use. Please see the documentation linked by @tytan652 above. The linked comment also has an example config that you can use.

Duplicate of https://github.com/flatpak/xdg-desktop-portal/issues/1077

**Closed by GeorgesStavracas** 2023-10-09 16:34 UTC

**Comment by Frontear** [comment] 2023-10-12 13:58
Hi there, Hyprland user here. This is not a flatpak issue, but instead an Arch issue because they are not packaging the file that is required for hyprland portals. This file is meant to be installed at `/usr/share/xdg-desktop-portals/hyprland-portals.conf` (see the relevant line in the https://github.com/hyprwm/Hyprland/blob/main/Makefile#L72)
