### ISSUE TITLE
Future file/folder access

### ISSUE THREAD

**Issue by MartinBriza** [flatpak/xdg-desktop-portal#133] opened 2017-11-29 17:25 UTC
Hi,
I think portals should provide access to folders (and files too, probably) even after the application was closed and opened again.

A typical use case for this is a music player that maintains my music collection. I store my music on my portable drive - now assume this is always mounted on /mnt/music. In the app, I specify I want to listen to music from ~/Music but also from /mnt/music. The next time I start this app, it doesn't have the access to that folder and have to add it to the collection again. Meanwhile, I'd expect it to be able to manage it right away.

This would probably have to be a completely new call in the API and it's most likely not mappable to the current APIs so it's likely only flatpak-aware apps would take advantage of this feature.
A similar feature is implemented in the Windows UWP platform [1].

[1] https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.AccessCache.StorageApplicationPermissions

**Comment by TingPing** [comment] 2017-11-29 17:40
> This would probably have to be a completely new call in the API

Another possibility being just adding to the UI of the existing FileChooser portals to add a persistence option similar to the read-only option.

**Comment by matthiasclasen** [comment] 2017-12-17 15:14
It should be persistent already. We export files to the document portal.

**Comment by mcatanzaro** [comment] 2023-09-27 18:46
There's a more detailed proposal for the same thing in #334, so I suggest we close this request as a duplicate of that one.

**Comment by GeorgesStavracas** [comment] 2023-09-27 22:47
Duplicate of https://github.com/flatpak/xdg-desktop-portal/issues/334

**Closed by GeorgesStavracas** 2023-09-27 22:47 UTC
