### ISSUE TITLE
FileChooser dialog window opened by portal is not focused by default on Xorg / X11, preventing keyboard navigation and shortcuts

### ISSUE THREAD

**Issue by nekohayo** [flatpak/xdg-desktop-portal#991] opened 2023-03-23 22:10 UTC
I hope this is the right place/component to report this on... it seems the portal's FileChooser window (in the case where it opens the GTK4 filechooser) does not get properly focused by default, on Fedora 38 running a GNOME Xorg/X11 session.

I have tested with the flatpak version of Evince (from flathub), and with the Fedora-provided RPM version of Firefox 111.

In Firefox, I went to `about:config` and set `widget.use-xdg-desktop-portal.file-picker` to `1` to be able to use the GTK4 filechooser through the portal.

In both apps (Evince, Firefox, and probably others), if you press Ctrl+O to open a file, the FileChooser will show up on top but it will not be focused, and so keyboard shortcuts or navigation won't work. Namely, these are the symptoms that are easy to verify:
* The `Esc` key will not dismiss the FileChooser dialog spawned by the portal, until you click the FileChooser window first
* The keyboard's arrow keys (ex: up/down) will not let you navigate the filechooser; instead, it will scroll the window underneath (ex: the website shown by Firefox, or the document shown by Evince)

**Comment by nekohayo** [comment] 2023-03-24 14:27
Thanks for the pointers, I have refiled the ticket as https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/75 :)

**Comment by smcv** [comment] 2023-03-26 10:03
Closing this as not our bug for now. It would be appropriate to reopen this if the root cause of the x-d-p-gnome bug turns out to be not getting enough information passed through x-d-p to be able to implement the desired UI.

**Closed by smcv** 2023-03-26 10:03 UTC
