### ISSUE TITLE
Flatpak: file paths in /var/data, etc. not handled by OpenURI portal

### ISSUE THREAD

**Issue by leamas** [flatpak/xdg-desktop-portal#592] opened 2021-06-15 16:20 UTC
Our application OpenCPN (www.opencpn.org) uses plugins which are dl-loaded flatpak extensions. Some of these have a need to display a local file like Help.html using the host browser. This should work using the sandboxed xdg-open if I have understood this, but it doesn't.

A test case: after loading our Shipdriver plugin we have a file test.html available in the sandbox as  /var/data/opencpn/plugins/ShipDriver_pi/data/test.html. If this file is fed to xdg-open in the sandbox it silently fails to display the file.

OTOH, displaying a file from the main application like /app/share/opencpn/authors.html  works just fine.

---
OS: Fedora 33
Flatpak: 1.10.2

Steps to reproduce (requires a x86_64 box):
  - Start org.opencpn.OpenCPN using `--command=bash`
  - Start application: `$ /app/bin/opencpn &`
  - In the application, click the top-left Options icon, the one under the hamburger.
  - Select the Plugins tab
  - Push the Import Plugin button
  - Import the attached plugin
  - In the list above the Import button, scroll down to the Shipdriver plugin
  - Push the Install button.
  - Check the "enabled" checkbox.
  - In the sandbox shell, try to open the file test.html:
    `$  xdg-open /var/data/opencpn/plugins/ShipDriver_pi/data/test.html`
  - Watch nothing happen

Expected results:
  - The test file should be displayed
  
Actual results:
   - Nothing displayed, return code zero, no error messages. 

[ShipDriver-2.6.3.0-+2106151524.f666917_flatpak-18.08-x86_64.tar.gz](https://github.com/flatpak/xdg-desktop-portal/files/6657134/ShipDriver-2.6.3.0-%2B2106151524.f666917_flatpak-18.08-x86_64.tar.gz)

**Comment by smcv** [comment] 2021-06-15 16:48
> we have a file test.html available in the sandbox as `/var/data/opencpn/plugins/ShipDriver_pi/data/test.html`

Oh, I might have misunderstood you on the mailing list. Are these plugins downloaded at runtime by the app itself, rather than being Flatpak extensions that are downloaded out-of-band by Flatpak?

I think this might be a problem that is specific to using `/var/data`. If you access the file via `$XDG_DATA_HOME` (which expands to something like `/home/you/.var/org.opencpn.OpenCPN/data` and is a separate mount point for the same directory as `/var/data`), does it work?

I can reproduce something similar: probably any app would work for this, I used `org.gnome.Recipes`.

```
host% flatpak run --command=bash org.gnome.Recipes
[📦 org.gnome.Recipes ~]$ echo "hello, world!" > $XDG_DATA_HOME/hello.txt
[📦 org.gnome.Recipes ~]$ xdg-open $XDG_DATA_HOME/hello.txt
(portal dialog pops up)
[📦 org.gnome.Recipes ~]$ xdg-open $XDG_DATA_HOME/hello.txt
(nothing happens)
```

**Comment by leamas** [comment] 2021-06-15 16:58
>  Are these plugins downloaded at runtime by the app itself, rather than being Flatpak extensions that are downloaded out-of-band by Flatpak?

Yes.

>  If you access the file via $XDG_DATA_HOME [snip], does it work?

No :( 

Same result: Nothing displayed, no error messages, return code 0.

**Comment by leamas** [comment] 2021-06-15 17:10
Furthermore, your $XDG_DATA_HOME/hello.txt testcase does not work for me either. But displaying files form the main application under /app/share works just fine.

Is our manifests broken somehow?
  - plugin: https://github.com/leamas/shipdriver_pi/blob/master/flatpak/org.opencpn.OpenCPN.Plugin.shipdriver.yaml
  - main application: https://github.com/OpenCPN/OpenCPN/blob/master/flatpak/org.opencpn.OpenCPN.yaml

"puzzled"

**Comment by smcv** [comment] 2021-06-15 17:11
Hmm, what exact command are you using to try to open it via `$XDG_DATA_HOME`? `xdg-open $XDG_DATA_HOME/opencpn/plugins/ShipDriver_pi/data/test.html` or something else?

And what does `realpath $XDG_DATA_HOME/opencpn/plugins/ShipDriver_pi/data/test.html` say?

**Comment by smcv** [comment] 2021-06-15 17:13
Oh, you're using `--filesystem=home` so your `$XDG_DATA_HOME` might not be the same place as `/var/data`.

Also try `xdg-open "$HOME/.var/app/$FLATPAK_ID/data/opencpn/plugins/ShipDriver_pi/data/test.html"` perhaps.

**Comment by leamas** [comment] 2021-06-15 17:16
It's expanded already by bash. In my history I have
` xdg-open /home/mk/.var/app/org.opencpn.OpenCPN/data/test.html` Same sad result.

XDG_DATA_HOME is /home/mk/.var/app/org.opencpn.OpenCPN/data

Using `xdg-open "$HOME/.var/app/$FLATPAK_ID/data/opencpn/plugins/ShipDriver_pi/data/test.html`: Same result. The path is correct though, the file is visible.

**Comment by smcv** [comment] 2021-06-15 17:19
Does `/home/mk/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/ShipDriver_pi/data/test.html` exist when looking at it from the host system?

The reason I asked you for the `realpath` of these various paths is that symbolic links matter: what `xdg-desktop-portal` will see in `/proc` is the path after following symbolic links.

**Comment by leamas** [comment] 2021-06-15 17:21
> Does /home/mk/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/ShipDriver_pi/data/test.html exist when looking at it from the host system?

Yes

    $ realpath $XDG_DATA_HOME/opencpn/plugins/ShipDriver_pi/data/test.html
    /home/mk/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/ShipDriver_pi/data/test.html

**Comment by smcv** [comment] 2021-06-15 17:23
Running `xdg-desktop-portal -vr` on the host system, then repeating `xdg-open /var/data/opencpn/plugins/ShipDriver_pi/data/test.html` and `xdg-open /home/mk/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/ShipDriver_pi/data/test.html`, might give you more information.

**Comment by leamas** [comment] 2021-06-15 17:26
Indeed. Got this
`XDP: Rejecting open request for /home/mk/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/ShipDriver_pi/data/test.html as opening not writable but fd is writable
`

Any idea what this means?

**Comment by leamas** [comment] 2021-06-15 17:28
Using the /var/opencpn/data path I get `XDP: Rejecting open request as fd has no path associated to it`

**Comment by smcv** [comment] 2021-06-15 17:36
> Using the /var/opencpn/data path I get `XDP: Rejecting open request as fd has no path associated to it`

I think you mean `/var/data/opencpn`? Please be precise, it matters when we are dealing with several similar paths.

That's the issue I *thought* I was fixing. #591 should make this behave like the other one.

> `XDP: Rejecting open request for /home/mk/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/ShipDriver_pi/data/test.html as opening not writable but fd is writable `

What runtime are you using and what is `xdg-open --version`? This might be flatpak/flatpak#3879 which was fixed in 1.0.3.

**Comment by leamas** [comment] 2021-06-15 17:51
> I think you mean /var/data/opencpn?

Yes, sorry...

     $ xdg-open --version
    1.0.1

The runtime is  the old 18.08, we are in the transitition phase. Should I check using 20.08?

**Comment by smcv** [comment] 2021-06-15 18:01
The updated flatpak-xdg-utils in either 19.08 or 20.08 should fix this. Please try with `flatpak run --command=bash --runtime-version=20.08` or similar, to confirm that. I think 18.08 is EOL, so there will be no updates to that branch.

I hope you will find that `xdg-open $XDG_DATA_HOME/opencpn/plugins/ShipDriver_pi/data/test.html` will work in 19.08 or 20.08. Your actual *app* might not run under 19.08 or 20.08 yet, but at least you'll know whether that upgrade will help with this issue.

`xdg-open /var/data/opencpn/plugins/ShipDriver_pi/data/test.html` will probably still not work. #593 should fix that.

**Comment by leamas** [comment] 2021-06-15 18:08
Underway, this will take some time since I need to rebuild the plugin for 20.08 (no plugin, no test file). I'm also runnig out of time here and now, but will report in few hours or so. (

our app already runs under 20.08 in the beta branch, so that part is no problem. It's just the plugin.

Many thanks for all your help so far!

**Comment by smcv** [comment] 2021-06-15 18:38
You don't really need to rebuild the plugin to test this, you just need any random HTML file somewhere below `/var/data`.

**Comment by leamas** [comment] 2021-06-15 19:26
Wanted to test the while thing. Did that, and it works just fine. 

Many thanks for your help. Sorry for abusing the issues mechanism with something which turned out to be a silly user needing some assistance.

Fixed in 20.08. Closing

**Comment by smcv** [comment] 2021-06-15 20:13
Does the path under `/var/data` work with 20.08? I would be surprised if it does, although #593 might well fix it.

**Comment by leamas** [comment] 2021-06-15 20:18
No, it doesn't.   xgd-open is at 1.0.4.

**Comment by smcv** [comment] 2021-06-15 20:27
OK, then we're down to just the issue that I thought I was solving!

**Comment by leamas** [comment] 2021-06-15 20:30
For me, it's kind of a relief that we actually have a bug here and not just silly me

**Closed** 2021-07-26 16:33 UTC
