### ISSUE TITLE
What is the correct way to open URLs from application?

### ISSUE THREAD

**Issue by BryanQuigley** [flatpak/xdg-desktop-portal#519] opened 2020-07-31 19:15 UTC
Trying to figure out the correct way to make a link work (started with https://github.com/flathub/de.uni_heidelberg.zah.GaiaSky/issues/1 links don't work - app I am working on).

Decided to see what other apps do and found 
flathub/gedit.  Help -> About > gedit.org | opens that webpage as a text file in gedit itself.
flathub/Rhythmbox Help-> About -> Rhythmbox website works as expected.
flathub/LibreOffice links open in external browser correctly
flathub/Steam - links open in external browser correctly

**Comment by TingPing** [comment] 2020-07-31 21:55
So the application looks like its written in Java which makes it annoying and I'm not familiar with it. The simple solution is for it to execute `xdg-open https://example.org` and it will just work inside of Flatpak.

**Comment by felipeborges** [comment] 2020-08-26 09:43
clicking on gedit.org opens the website in a browser here too, as expected.

**Comment by BryanQuigley** [comment] 2020-08-26 16:29
I've helped find another case where GaiaSky doesn't have working links.

@felipeborges can we compare setups? It's possible that I have something wrong on my system.  
Ubuntu 20.10 dev
org.gnome.gedit                                               3.36.2            stable          flathub               system
ostree                                        2020.5-1
xdg-desktop-portal                            1.6.0-1
flatpak                                       1.8.1-2

xdg-open http://www.gedit.org does do the right thing.

**Comment by felipeborges** [comment] 2020-08-27 08:19
Gotcha, I was running an older version of gedit. This seems like a regression.

**Comment by BryanQuigley** [comment] 2020-09-22 17:07
Upstream (https://gitlab.com/langurmonkey/gaiasky/-/issues/337#note_416407044) traced it to https://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/java.desktop/unix/classes/sun/awt/X11/XDesktopPeer.java#l119.  What should Java be doing there instead?

**Comment by hadess** [comment] 2020-09-22 17:37
Is this really using [`gnome_url_show()`](https://developer.gnome.org/libgnome/stable/libgnome-gnome-url.html#gnome-url-show) from the 2.x era libgnome? That's been deprecated for the best part of 10 years.

**Comment by hadess** [comment] 2020-09-22 17:58
I don't know what Java should be using, but I'm pretty certain that `gnome_url_show()` didn't know anything about [`x-scheme-handler`](https://specifications.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-latest.html#idm45070737692352)

**Comment by TingPing** [comment] 2020-09-22 18:35
Java should probably be using `g_app_info_launch_default_for_uri_async()`.

**Comment by nbenitez** [comment] 2021-01-16 21:58
> Java should probably be using `g_app_info_launch_default_for_uri_async()`.

A more short term solution would be to patch our flathub openjdk extension to use that api or to just launch a `xdg-open` command. I proposed that on the following issue:
https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11/issues/15

**Comment by GeorgesStavracas** [comment] 2023-10-13 19:34
Given the proposals above, and the investigation that was done, I'm considering this out of scope for XDG desktop portal

**Closed by GeorgesStavracas** 2023-10-13 19:34 UTC
Labels: question
