### ISSUE TITLE
--filesystem=… as a portal

### ISSUE THREAD

**Issue by swick** [flatpak/xdg-desktop-portal#440] opened 2020-02-13 16:34 UTC
There is applications (IDEs, Blender, kicad, …) which work on a bunch of files each having dependencies with other files. The files also have a meaning to the user and should be easily accessible from within a file browser. Sometimes the location of the files is fixed (shared network mount, external hard drives, cloud sync).

None of the existing flatpak/xdg-portal features really supports this.

Saving the files somewhere in ~/.var/app/ is not possible (fixed location, easily accessible).
Using the document portal is not possible (files with dependencies).
The filesystem override is coming the closest but the key problem here is that right now it requires the user to be aware of the functionality and then issue a command in the terminal. A settings GUI to add a filesystem mount makes this better but the application can not guide the user to the settings easily and the resulting UX is just horrible.

It would be nice to have a portal which opens a GUI to add a filesystem mount and have new mounts appear in the running sandbox.

Right now most of the mentioned apps just give full access to the home directory. I'm aware that this is a somewhat risky proposition. Maybe the portal should be guarded behind a --allow=new-fs-mount or something like that.

**Comment by TingPing** [comment] 2020-02-13 18:29
This is a duplicate of #200 I'd say.

**Closed by TingPing** 2020-02-13 18:29 UTC

**Comment by swick** [comment] 2020-02-13 19:50
You're right, sorry for the noise. Missed the issue somehow.
