### ISSUE TITLE
File chooser portal isn't using the document portal

### ISSUE THREAD

**Issue by WhyNotHugo** [flatpak/xdg-desktop-portal#680] opened 2021-12-13 17:26 UTC
I'm trying to get applications like Firefox and Telegram to work with the File Chooser portal + Document portal.

I've tried Firefox configuring it with `widget.use-xdg-desktop-portal=true` and even  `GTK_USE_PORTAL=1`. Firefox _does_ use the file-chooser portal, but the portal does not return a URI pointing into the document portal filesystem (as documented for [org.freedesktop.portal.FileChooser](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.FileChooser)); the returned file path is the original absolute path to the file in the host.

Given that the file chooser _is_ being used, but the returned URI is the original path, I don't think that Firefox is at fault here, I think it's somewhere in the file chooser portal itself, or, more likely, user misconfiguration of some sort (though I can't quite pin-point what).

I've used Firefox as an example here, but the same issue is present with Telegram Desktop.

## Reproduction steps

1. The simplest way is to just run a native firefox with `widget.use-xdg-desktop-portal=true`.
2. Press <kbd>ctrl</kbd>+<kbd>o</kbd> to open a file.
3. Pick some image file on your `$HOME`.
4. Note that firefox opens the path to the original file, indicating that the portal did not return a path a document-portal mount.

This is a problem when using native applications with, e.g., firejail, since they are restricted from view arbitrary locations in `$HOME`.

OTOH, Firefox-in-Flatpak _does_ work properly, which makes me suspect that the portals might have some specific tweak for that setup. Is that so? Any hints of what I should check or be doing differently?

---

Related: https://github.com/netblue30/firejail/issues/4716

**Comment by WhyNotHugo** [comment] 2021-12-13 20:43
My bad, I didn't clarify this in the initial description: I've running the Firefox via firejail. Firejails sandboxes the application in a way that's _similar_ to Flatpak in some ways. firejail actually mounts the hosts's /usr (e.g.: it uses the files provided by the OS's native package manager), but mounts, in this case, an empty `$HOME`.

Does the file-chooser behave differently for native applications vs flatpak applications? How can I spawn it in a way that behaves like it does for flatpak apps?

**Comment by swick** [comment] 2021-12-13 20:50
> Does the file-chooser behave differently for native applications vs flatpak applications?

Yes. 

> How can I spawn it in a way that behaves like it does for flatpak apps?

You can't. It handles flatpak clients differently from host clients. It detects if the process is from flatpak by looking for the /.flatpak-info file in the process fs tree. If you want x-d-p to work properly with firejail then firejail has to set up the sandbox in a way that it can be reliably identified and then write that identification code in x-d-p.

**Comment by WhyNotHugo** [comment] 2021-12-13 21:03
> You can't. It handles flatpak clients differently from host clients. It detects if the process is from flatpak by looking for the /.flatpak-info file in the process fs tree. If you want x-d-p to work properly with firejail then firejail has to set up the sandbox in a way that it can be reliably identified and then write that identification code in x-d-p.

I'd be interested in writing some form of wrapper that could spawn the portal for firejail'd native applcations. Do you have pointers on how the portal should be invoked? I _am_ using `xdg-dbus-proxy`, if that's somehow involved.

**Comment by WhyNotHugo** [comment] 2021-12-20 23:30
I'd initially misunderstood part of your explanation, I now see that the portal checks _the process_'s filesystem view (e.g.: via: `/proc/PID/root/.flatpak-info`).

How can the portal be certain of the caller's PID? I don't see D-Bus exposing this.

**Comment by swick** [comment] 2021-12-20 23:57
> How can the portal be certain of the caller's PID? I don't see D-Bus exposing this.

org.freedesktop.DBus.GetConnectionUnixProcessID

If you want to use the same method of authentication it is required that

1. all processes must always have the /.flatpak-info file with the correct content in their filesystem view 
2. all processes communicating with dbus must not be susceptible to PID reuse

For flatpak this is achieved by
1. restricting the permissions and syscalls in the sandbox via bwrap
2. only let xdg-dbus-proxy communicate with the dbus daemon as well as special handling of the xdg-dbus-proxy process so that it can't be killed by other processes in the sandbox

All of that is kind of subtle. The alternative is to let the containerization process (e.g. flatpak, snap, firejail…) request a new socket from the dbus daemon, attach the appid to the socket and then mount that in the sandbox (https://gitlab.freedesktop.org/dbus/dbus/-/issues/171).

**Comment by Erick555** [comment] 2021-12-27 20:11
Document portal is quite [hardcoded](https://github.com/flatpak/xdg-desktop-portal/blob/master/src/xdp-utils.c#L160) around flatpak/snap so without patching the x-d-p you may not be able to use it.

**Comment by WhyNotHugo** [comment] 2021-12-27 20:58
I didn't notice the snap-specific bits. I had assumed that `xdg-desktop-portal` was flatpak-specific.

It might be feasible to extract the sandbox-specific bits somehow. Or maybe standardise how some sandbox/app metadata is obtained across flatpak *and* snap. The resulting interface would likely be better for things like firejail to integrate and be more decoupled from flatpak's internals.

What does `xdg-desktop-portal` need to know for this particular scenario? It needs to determine which xdg-dbus-proxy corresponds to that process, right? Does it need a `pid`, or a path to a socket?

**Comment by Erick555** [comment] 2021-12-28 12:47
Document portal needs to know if the app has permission to access particular file or not, i.e. https://github.com/flatpak/xdg-desktop-portal/blob/master/document-portal/document-portal.c#L648

**Comment by GeorgesStavracas** [comment] 2023-10-05 16:09
As far as I can see, this is just a consequence of #737. I'm going to close this one as a duplicate, please reopen if necessary.

Duplicate of #737

**Closed by GeorgesStavracas** 2023-10-05 16:09 UTC
