### ISSUE TITLE
README.md broken link

### ISSUE THREAD

**Issue by supertobi** [flatpak/xdg-desktop-portal#160] opened 2018-02-15 10:27 UTC
The link to http://flatpak.org/xdg-desktop-portal/portal-docs.html in this line "Documentation for the available D-Bus interfaces can be found here." in the README.md is broken. (404 Not Found)

**Comment by TingPing** [comment] 2018-02-15 10:34
Duplicate of #138

**Closed by TingPing** 2018-02-15 10:34 UTC
