### ISSUE TITLE
GTK_USE_PORTAL=1 breaks GTK apps antialiasing and mouse cursor size

### ISSUE THREAD

**Issue by medmedin2014** [flatpak/xdg-desktop-portal#1123] opened 2023-10-03 22:00 UTC
```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.5-1-MANJARO (64-bit)
Graphics Platform: Wayland
```
After finishing the following upgrade and rebooting

xdg-desktop-portal (1.16.0-3 -> 1.18.0-2)
xdg-desktop-portal-gtk (1.14.1-1 -> 1.14.1-3)
xdg-desktop-portal-kde (5.27.8-1 -> 5.27.8-2)

Firefox tabs got bigger, the mouse cursor became large in all GTK apps, and font is not anti-aliased.

Removing GTK_USE_PORTAL=1 seems to fix the issue, but my apps are forced to use those ugly GTK open/save dialogs.

NB: Before upgrading, GTK_USE_PORTAL=1 was working fine.

![Screenshot_20231003_203113](https://github.com/flatpak/xdg-desktop-portal/assets/7027319/9e80c98b-50bc-4d16-9c58-4fd362d488eb)

**Comment by GeorgesStavracas** [comment] 2023-10-04 00:43
Duplicate of https://github.com/flatpak/xdg-desktop-portal/issues/1112

**Closed by GeorgesStavracas** 2023-10-04 00:43 UTC

**Comment by guss77** [comment] 2024-12-03 02:08
I have the same issue after updating to `xdg-desktop-portal` 1.19.0 (on KDE Neon release channel). I also have `xdg-desktop-portal-gtk=1.15.1-1build2` and `xdg-desktop-portal-kde=6.2.4-0zneon+24.04+noble+release+build8` installed.

Reverting to `xdg-desktop-portal` 1.18.4 fixes the issue, as well as removing `GTK_USE_PORTAL` from the environment (or setting it to `0`), or running under XWayland.

This is a problem not only for flatpak apps but also for natively installed apps, and I don't think it is related to #1112 - as the broken anti aliases fonts are definitely from the Breeze theme.
