### ISSUE TITLE
Portal for granting permanent access to an arbitrary directory

### ISSUE THREAD

**Issue by allanday** [flatpak/xdg-desktop-portal#1116] opened 2023-09-27 16:38 UTC
To my knowledge, there's no way for an app to be granted permanent access to an arbitrary directory. This can be necessary for apps that manage content which isn't stored according to the standard XDG folders.

For example, someone might want to use an app to manage a music or photo library that is stored on a different drive, or which is saved in a location where it can be synchronised by a sync client.

This is a longstanding request that we have for gnome-music: https://gitlab.gnome.org/GNOME/gnome-music/-/issues/69

**Comment by Mikenux** [comment] 2023-09-27 17:41
Related issues: https://github.com/flatpak/xdg-desktop-portal/issues/133, https://github.com/flatpak/xdg-desktop-portal/issues/334.

Also, thinking of a design for drag and drop would be nice (see https://github.com/flatpak/xdg-desktop-portal/issues/663).

**Comment by mcatanzaro** [comment] 2023-09-27 18:44
I think this one is most closely a duplicate of #133.

**Comment by mcatanzaro** [comment] 2023-09-27 18:45
Actually they're really nearly the same. Let's keep #334 open since that one has the most detailed proposal, and threat this and #133 as duplicates.

**Comment by GeorgesStavracas** [comment] 2023-09-27 22:46
Duplicate of #334

**Closed by GeorgesStavracas** 2023-09-27 22:46 UTC
