### ISSUE TITLE
File chooser not opening in Flatpak

### ISSUE THREAD

**Issue by amogusussy** [flatpak/xdg-desktop-portal#1126] opened 2023-10-04 21:51 UTC
If I click on a file chooser button in any flatpak app, it doesn't open any file chooser.
For example, if I run `flatpak run com.github.marinm.songrec`, then click on the file chooser button, no menu shows up, and this is printed to the terminal:
```
(songrec:2): Gtk-WARNING **: 22:45:14.337: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.FileChooser” on object at path /org/freedesktop/portal/desktop
```
I've already got `xdg-desktop-portal-gtk` installed, yet it doesn't show up.

**Comment by GeorgesStavracas** [comment] 2023-10-05 16:11
What version of XDG Desktop Portal are you using? Which distribution? Which desktop environment? Please provide more information, as it is it's impossible to diagnose the issue.

**Comment by SoulHarsh007** [comment] 2023-10-05 17:17
Hello, I have a similar issue. It seemed to work fine when I was using version 1.16.0, but the issue seems to be after I upgraded to version 1.18.0. I am using Arch Linux. I have tested this on i3wm (X11) and hyprland (Wayland). I am also willing to provide any additional logs if it can help identify this issue.

**Comment by GeorgesStavracas** [comment] 2023-10-05 17:33
Do Arch packagers or hyprland developers or i3wm developers provide a config file for the portal? Vesion 1.18 introduces a config-based mechanism, GNOME one, KDE also ships one. I'm not sure what's the policy defined by self-assembled window managers. You may need something like this: https://github.com/flatpak/xdg-desktop-portal/issues/1077#issuecomment-1715896552.

If the config above works for you, than this bug can be considered a duplicate.

**Comment by SoulHarsh007** [comment] 2023-10-05 17:49
I have added the configuration snipped that was shipped with `xdg-desktop-portal-hyprland` packages to `$HOME/.config/xdg-desktop/portal/hyprland-portals.conf`. But it still does not seem to work. The contents of the file are similar to the one mentioned in the linked comment.

```ini
[preferred]
default=hyprland
````

**Comment by SoulHarsh007** [comment] 2023-10-05 18:01
I have also tried adding a configuration manually for i3wm to use gtk as default portal. I added it to `$HOME/.config/xdg-desktop-portal/i3-portals.conf`. This also does not seem to help. The file content if it helps:
```ini
[preferred]
default=gtk
```

**Comment by SoulHarsh007** [comment] 2023-10-05 18:09
My bad, the configuration part fixes the issue. I had to reboot after addition the configuration files, I was just logging out and logging back in.

**Comment by GeorgesStavracas** [comment] 2023-10-05 18:48
Okay, treating it as a duplicate of #1077. Thanks for testing it.

**Closed** 2023-10-05 18:48 UTC
Labels: need more info
