### ISSUE TITLE
Add a portal to grant access to new folders

### ISSUE THREAD

**Issue by bilelmoussaoui** [flatpak/xdg-desktop-portal#327] opened 2019-05-19 23:32 UTC
Context:
Currently, for Fragments, a torrent client, we grant access by default to only XDG Downloads which works perfectly fine. Now, users often want to download their torrents to a home server or in another location. To avoid asking for home or host permission by default, having the possibility to select a folder using the GtkFileChooserNative and use a portal to request access to that folder for only this time, forever or to refuse that would solve also the issue of Music players that asks for access to the home filesystem.
Related upstream: https://gitlab.gnome.org/World/Fragments/issues/40
https://gitlab.gnome.org/World/Fragments/merge_requests/54

Portal: A new portal to grant access to a specific folder for a period of time.

**Comment by TingPing** [comment] 2019-05-20 03:13
Duplicate of #200

**Closed by TingPing** 2019-05-20 03:13 UTC
