### ISSUE TITLE
Get real path from FileChooser portal

### ISSUE THREAD

**Issue by JakobDev** [flatpak/xdg-desktop-portal#788] opened 2022-05-05 08:32 UTC
The file chooser Portal gives you currently access to a file/directory the user selects. The file can be accessed from inside the sandbox in the directory /run/user/(uid)/doc. The file access itself works great, but the path is the Problem. Many Apps display the Path e.g. in a recent files menu or showing the file the user is currently editing.

Showing the /run path is a very bad user experience.  The thing remains from the real path is the file name. So the User gets in a recent files list a list of /run/random_stuff/filename. If you have multiple files with the same name in the list, it is very confusing. e.g. the file which contains the list for needed Python packages is named requirements.txt. If you work with multiple requirements.txt, you can't tell from looking at the list with 7run paths, which is which.

Another example would be a text editor, that shows the Path of the file that is open. If the User has the File some time open in the Background and get's back the work, it is hard to say which file he/she is currently editing.

**Comment by vchernin** [comment] 2022-05-14 16:15
https://github.com/flatpak/xdg-desktop-portal/issues/475

**Comment by GeorgesStavracas** [comment] 2023-10-05 16:10
Duplicate of #475

**Closed by GeorgesStavracas** 2023-10-05 16:10 UTC
