### ISSUE TITLE
Celluloid prevents USB drive from being unmounted

### ISSUE THREAD

**Issue by zookeeper76** [flatpak/xdg-desktop-portal#902] opened 2022-10-20 01:28 UTC
When using Celluloid packaged as a Flatpak, I always have the following problem. Mount a USB drive and open a video file you have copied to this drive, the video file can be of any size it does not change the outcome. Start playing the file and then close Celluloid. Next try unmounting the USB drive. You will get an error saying that the volume is busy and that the drive should not be removed. No matter how long you wait, something in the background is preventing the drive to be removed. The only way to work around this is to log out of your session and log back in,,,

For info, I'm using Fedora Silverblue 37. I can say that this issue does not affect Celluloid installed as an RPM package, it only happens when using the Flatpak.

Thanks for looking it this.

**Comment by rusty-snake** [comment] 2022-10-20 11:58
#689 #721

**Comment by GeorgesStavracas** [comment] 2022-12-12 19:25
Duplicate of https://github.com/flatpak/xdg-desktop-portal/issues/689

**Closed by GeorgesStavracas** 2022-12-12 19:25 UTC
