### ISSUE TITLE
[Feature request] A clipboard manager portal

### ISSUE THREAD

**Issue by ofourdan** [flatpak/xdg-desktop-portal#743] opened 2022-03-24 14:11 UTC
On a virtual machine running Wayland, one of the X11 clients still started automatically (hence running on Xwayland) is [Spice vdagent](https://gitlab.freedesktop.org/spice/linux/vd_agent).

One of the features Spice vdagent does is to “support of copy and paste (text and images) between the active X-session and the client. This supports both the primary selection and the clipboard.”

This is not possible with a Wayland session (short of using [wlr-data-control](https://github.com/swaywm/wlr-protocols/pull/25) which is not available outside of wlroots based compositors) because the clipboard manager is accessible only to the Wayland compositor and there is no standard way to access the clipboard manager under Wayland (that I am aware of).

The ability to read and write entries in the clipboard manager can be useful for a variety of clients, e.g.:

 * Virtual machines to replicate what spice-vdagent does
 * Remote desktop applications to copy/paste content to or from the remote host
 * Keyboard and mouse sharing software such as [Barrier](https://github.com/debauchee/barrier)/[Synergy](https://github.com/symless/synergy-core)/[input-leap](https://github.com/input-leap/input-leap)
 * Password managers to automatically copy a password for the user to paste in an application
 * etc.

Obviously, accessing the clipboard should be allowed to a limited and controlled number of clients, which would make it a good candidate for the desktop portal, possibly.

Sorry in advance if this has been considered before, I haven't managed to find an existing request for this.

**Comment by Sodivad** [comment] 2022-03-25 09:54
> short of using https://github.com/swaywm/wlr-protocols/pull/25 which is not available outside of wlroots based compositors
KWin implements it too

**Comment by salmanmlk** [comment] 2022-03-29 20:16
> because the clipboard manager is accessible only to the Wayland compositor and there is no standard way to access the clipboard manager under Wayland (that I am aware of).

It is possible to access the clipboard under wayland by having a wayland client present a surface/window on the screen. When keyboard enters this surface, then that wayland client can interact with the clipboard (read selection or set selection, for example). But I agree that this isn't a viable approach for some applications especially when the presented surface is only meant for interacting with the clipboard.

> Remote desktop applications to copy/paste content to or from the remote host

Agreed. It will be nice to have portal/APIs to read/write from clipboard.

**Comment by jadahl** [comment] 2022-03-29 20:24
> Agreed. It will be nice to have portal/APIs to read/write from clipboard.

That should probably be part of the remote desktop API.

**Comment by jadahl** [comment] 2022-03-30 05:30
> Virtual machines to replicate what spice-vdagent does

I don't think the `vdagent` case is something that fits what portals are meant to solve; it works more like a driver than an application someone installs. Perhaps it should rather provide an API on the system bus that a DE interacts with in a way it sees fit.

> Remote desktop applications to copy/paste content to or from the remote host

As mentioned, seems like something that can be handled by the remote desktop portal, with explicit user consent etc.

> Keyboard and mouse sharing software such as [Barrier](https://github.com/debauchee/barrier)/[Synergy](https://github.com/symless/synergy-core)/[input-leap](https://github.com/input-leap/input-leap)

Perhaps also managable via a remote desktop API. The "private data leak" aspect here is identical.

> Password managers to automatically copy a password for the user to paste in an application

This is hard to reason without knowing how these actually behave. E.g. if one interacts with them using the upcoming global shortcut portal, one could treat being triggered via it as being allowed to interact with the clipboard some way.

A generic "clipboard manager" portal that is meant for actual clipboard managers I'm not convinced about.

**Comment by shdwchn10** [comment] 2022-06-29 14:13
I wonder if it will be possible with this portal to provide privacy of the clipboard, like in Android[^1][^2]?

[^1]: https://developer.android.com/about/versions/10/privacy/changes#clipboard-data
[^2]: https://developer.android.com/guide/topics/text/copy-paste#PastingSystemNotifications

**Comment by GeorgesStavracas** [comment] 2022-12-12 20:25
https://github.com/flatpak/xdg-desktop-portal/issues/843 is a duplicate, but since it holds most of the discussion, I'll close this one.

Duplicate of https://github.com/flatpak/xdg-desktop-portal/issues/843

**Closed by GeorgesStavracas** 2022-12-12 20:25 UTC
