### ISSUE TITLE
xdg-document-portal leaks FDs

### ISSUE THREAD

**Issue by felinira** [flatpak/xdg-desktop-portal#1008] opened 2023-04-24 22:39 UTC
Closing an app while having open files causes those FDs to leak.

Steps to reproduce:
* Open amberol for example, select a file to play
* Press Ctrl+q
* Look at `lsof -p $(pidof xdg-document-portal)`

The file that was opened is still being held open, in contrast to when the app closes the file by itself (eg. by switching to the next track)

**Comment by Redecorating** [comment] 2023-04-25 04:03
Seems related to https://github.com/flatpak/xdg-desktop-portal/issues/689, where having these files kept open makes it impossible to unmount filesystems

**Comment by xioren** [comment] 2023-05-02 18:56
I have done a little poking around to see if I could learn more about it. One thing I will note is that not all Flatpak apps cause this issue. For me the issue is with MPV, other apps such as my image viewer do not cause an issue. The problem is not solely with MPV though as I have seen other people with this issue with other Flatpak apps. I'm hoping for more discussion on this issue as it is a particularly egregious imo

**Comment by rusty-snake** [comment] 2023-05-02 19:00
Guess because your image viewer has `filesystem=` permission and dies not usw Portals.

**Comment by xioren** [comment] 2023-05-03 00:10
For what it's worth I am so far unable to reproduce this issue with the same distro and Flatpak version in a VM.

**Comment by xioren** [comment] 2023-05-03 01:54
@GeorgesStavracas can you provide some insight? For the methods contained in org.freedesktop.portal.Documents, those are to be called by the program wishing to use xdg-document-portal correct? I can't find them in the source code. If so that means its up to each individual program to specify weather they want a file for a session or indefinitely by using the ``persistent``` argument. 
```
IN h o_path_fd:
open file descriptor for the file to add

IN b reuse_existing:
whether to reuse an existing document store entry for the file

IN b persistent:
whether to add the file only for this session or permanently

OUT s doc_id:
the ID of the file in the document store
```

I'm trying to piggy back off what @teohhanhui referenced in [#4303](https://github.com/flatpak/flatpak/issues/4303#issuecomment-860527136). In my case every time I open a file, a new export shows up in ```/run/user/$UID/doc/```. So right now I have five exports and counting for the same file in the MPV directory, and they stay there even after closing the flatpak. I'm trying to figure out if that's normal behavior.

**Comment by xioren** [comment] 2023-05-09 21:58
Well according to Google Bard, which is able to review GitHub repos, there are two possible solutions. I have no idea if they work or are total nonsense but I will post them here anyway.

The first approach is apps using the xdg-document-portal need to close the files they open with:
```
gio_file_close(file, NULL);
```

Second, adding this code to ```xdg-desktop-portal.c```:

```
void xdg_desktop_portal_close_files(struct xdg_desktop_portal *portal) {
    // Get a list of all the files that are currently open.
    GList *files = g_hash_table_get_values(portal->files);

    // Iterate over the list of files and close them.
    for (GList *iter = files; iter != NULL; iter = iter->next) {
        GFile *file = G_FILE(iter->data);
        gio_file_close(file, NULL);
    }
    // Free the list of files.
    g_list_free(files);
}
```

**Comment by xioren** [comment] 2023-05-09 22:18
Furthermore, while I was unable to get a response from @GeorgesStavracas about the multiple exports for the same file, my assumption is that this is not normal behavior. For what it's worth Google Bard agreed and suggested that issue is related to the file descriptor bug. It provided a variation of the function above as a solution:

```
void xdg_desktop_portal_close_file(struct xdg_desktop_portal * portal, GFile *file) {
    // Close the file descriptor.
    gio_file_close(file, NULL);

    // Remove the file from the list of open files.
    g_hash_table_remove(portal->open_files, file);
}
```

**Comment by GeorgesStavracas** [comment] 2023-10-04 00:41
Duplicate of #689

**Closed by GeorgesStavracas** 2023-10-04 00:41 UTC
Labels: bug, portal: documents, needs diagnosis
