### ISSUE TITLE
The open dialog wants to choose a file instead of a directory.

### ISSUE THREAD

**Issue by qg0** [flatpak/xdg-desktop-portal#441] opened 2020-02-18 13:59 UTC
The open dialog in the app Telegram wants to choose a file instead of a directory.

![74585432-2db83580-500f-11ea-9d9e-d06722c85d1b](https://user-images.githubusercontent.com/919099/74742563-66ffd800-5291-11ea-821e-65317806d71b.png)

Please see the details [here](https://github.com/telegramdesktop/tdesktop/issues/7211).

**Comment by TingPing** [comment] 2020-02-19 04:40
Not supported currently, Duplicate of #200

**Closed by TingPing** 2020-02-19 04:40 UTC
