### ISSUE TITLE
Screenshot portal without prompt

### ISSUE THREAD

**Issue by lionirdeadman** [flatpak/xdg-desktop-portal#649] opened 2021-10-16 02:58 UTC
This may seem dangerous but for screenshot applications, this sounds necessary from a design POV. Having a screenshot application which asks twice to screenshot would be quite awkward, I think.

Related : https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1970 , https://github.com/flameshot-org/flameshot/issues/1910

**Comment by lionirdeadman** [comment] 2021-10-16 14:51
I think it should be strictly easy to control so it shouldn't be metadata (and require something like Flatseal to change).

I think it should be a one-time prompt like there is for the background or camera permission. I suppose it wouldn't be a bad idea to make the permanency of it optional as to make the use case for it more flexible though.

**Comment by All3xJ** [comment] 2021-11-16 11:12
Is there any news about this annoying issue?

**Comment by Midnex** [comment] 2021-11-18 00:56
I hope you only have to give permission one time, and then from there it can do it everytime. This would be more secure than the old method, but less annoying then the current.

**Comment by kurobeats** [comment] 2021-11-21 08:28
Can I express how powerless this issue makes me feel in relation to Gnome development. The tone from the Gnome folks here: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1970 indicates to me this issue will not be resolved/is not considered an issue. Creating a Gnome related bug report is akin to shouting into the void, isn't it?

**Comment by DamirPorobic** [comment] 2021-11-21 10:59
They don't see the issue there but it's probably the same folks that doesn't take much screenshots so they don't feel the pain. As long as they're not made aware about the user frustration coming from this, they won't fix it am afraid.

**Comment by mcatanzaro** [comment] 2021-11-21 14:51
> Can I express how powerless this issue makes me feel in relation to Gnome development. The tone from the Gnome folks here: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1970 indicates to me this issue will not be resolved/is not considered an issue. Creating a Gnome related bug report is akin to shouting into the void, isn't it?

Honestly, your expectations are misplaced. Bypassing the screenshot portal is unacceptable, as it defeats the point of having the portal in the first place. Applications should not be able to screenshot your desktop without your permission. Removing the backdoor should not be controversial.

If you read up in this issue, we already have agreement on the path forward to enhance the screenshot portal. It's just waiting for a motivated developer to tackle it.

**Comment by VitalyAnkh** [comment] 2021-11-21 15:03
@kurobeats @DamirPorobic
The Gnome developers made this decision (don't allow external apps to use gnome's private API) for protecting the privacy of users and forbidding API abuse. They are also doing a redesign for the screenshot UI of gnome: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1954 

The Words accusing the developers of not caring about something are not true, and totally unconstructive.

**Comment by DamirPorobic** [comment] 2021-11-21 15:19
@VitalyAnkh I've spoken with Gnome developers (also same with KDE developers but they haven't disabled the private dbus yet) on few occasions about this topic, on tickets and on IRC and my impression was that this is for them a minor inconvenience. One of them told me even that this is a fair trad off, few clicks more but you get more security. So I don't see it as "not true" and even the "totally unconstructive" is debatable, user requirement sets the prio for features, if no one speaks up the developers that don't use this feature won't get the user pain. 

Not sure what the screenshot UI redesign to do with this issue, our problem is that we need to give permission for every screenshot instead of once like most people are used to like from mobile phone apps. 

@mcatanzaro is right, there is a suggestions that, when implemented, would fix our issues, I don't see any further discussion here.

**Comment by kurobeats** [comment] 2021-11-21 23:24
> Honestly, your expectations are misplaced. 

Maybe so but the action taken has now created a negative user experience. Forgetting my comments, I'm a voice in the crowd, think about the "regular user", they are going to see this behaviour and be confused by it because it's not something they have come to expect.

>Bypassing the screenshot portal is unacceptable, as it defeats the point of having the portal in the first place. Applications should not be able to screenshot your desktop without your permission. Removing the backdoor should not be controversial.

Let's keep in mind we are talking about a screenshotting tool here not a trojan (which I imagine we are trying to defend against here). Flameshot, for example, doesn't have to overcome hurdles to screenshot on Windows or MacOS.

> If you read up in this issue, we already have agreement on the path forward to enhance the screenshot portal. It's just waiting for a motivated developer to tackle it.

I'm very happy to hear it, but wouldn't it have been pragmatic to implement the solution before we do unexpected things to the user base?

**Comment by borgmanJeremy** [comment] 2021-11-21 23:51
Author of flameshot here, actually on MacOS you do have to grant a one time permission to record the the screen.

While I was annoyed this changed in gnome before we adjust the portal to only ask a single time, overall this will be a great compromise between ease of use and security. It also will be exactly the same as MacOS. I think my users will also find the one time prompt acceptable.

**Comment by Remzi1993** [comment] 2021-11-22 12:14
> Yeah, I think just a dialog that asks for that permissions with an option to make it permanent would in that case be the best, without any other selection option. Bonus points for additional parameter in the API call like "Include cursor" and "Include window decoration".
> 
> > That wouldn't apply the same to screencasts, but those are a separate portal.
> 
> Yes, I think it was a different API but I can imagine that they have similar issues if they haven't been fixed already.

Yeah, I understand the security concerns from the Gnome team, but it's also about giving users options. Give users the ability to give certain applications permission to do this and remember their choice.

Certain programs like Screenshot apps and screen capture/recording programs need this to work. And giving those programs permission every time gets tiring and not user friendly.

**Comment by dancojocaru2000** [comment] 2021-12-03 12:59
I'm rather amazed that people invoke "security" as a reason while undermining security by not thinking things through.

When a security feature is very annoying or even breaks software, it becomes an anti-feature. For example, when Telegram Desktop was failing to read files I was drag and dropping into it because the portal wasn't smart enough to see that drag and drop should give permissions for that file, I installed Flatseal and gave Telegram Desktop permissions to all files. Where's the security in that?

Any security features that are sufficiently irritating become just yet another annoying thing to turn off. They not only provide zero security, but are also an added annoyance.

While I appreciate the concern and I also appreciate that a decision was reached to implement the "remember this obvious choice" feature, I am disappointed that usability and actual security are not priorities and they are just an afterthought after users complain.

I would hope this is implemented and more care is taken in the future when "security" features are implemented, because for now I've gotten used to avoid Flatpaks in order to have actually functioning applications, and I'd love for that to change in the future.

**Comment by jf2048** [comment] 2021-12-03 14:28
@dancojocaru2000 IIRC that is not related to a security feature, it's missing functionality in the application and it needs to add support for the file transfer portal. Please follow the discussion here: https://github.com/flatpak/xdg-desktop-portal/issues/99

**Comment by kurobeats** [comment] 2021-12-07 23:16
Hi Team,
Can I request if this issue is being addressed? Totally fine if it isn't deemed an issue, I can revert to Xorg.

**Comment by All3xJ** [comment] 2021-12-24 15:33
Any news? This is not normal. Workflow can't be damaged this way..

**Comment by angordeyev** [comment] 2021-12-24 18:09
Very frustrating, please give user an option not to see the window every time, the great thing about Linux is flexibility and it should not be broken.

**Comment by All3xJ** [comment] 2021-12-26 09:03
I reported again to gnome upstream: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1970#note_1341047

**Comment by kurobeats** [comment] 2021-12-27 02:24
@All3xJ members of the team are claiming criticism of the bug they introduced as harassment (or something close to: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4895#note_1341442). I think it'll be best if people affected by this issue move to Xorg (it still works perfectly well!) or to a user friendly desktop environment (I've moved to Plasma), this bug isn't actively being worked on.

**Comment by refi64** [comment] 2021-12-27 03:24
There are **no objections** to having a one-time prompt for the portal; the other issues being linked are related to internal GNOME APIs being used for this, which was never correct in the first place and is an entirely separate API.

Please avoid the "any news on this" comments, they do nothing but clutter the thread. The issue has also been open for less than three months and will likely end up involving volunteer work contributed in developers' free time...so pardon the bluntness, but I'm pretty sure more time and energy has already been spent on this thread than saved by not having to perform a click.

**Comment by GeorgesStavracas** [comment] 2021-12-27 11:20
Temporarily locking due to too low signal-to-noise ratio. I'd encourage anyone who wishes to see this feature to go ahead and implement it in xdg-desktop-portal, and at least one frontend (GNOME, KDE, or wlroots).

**Comment by GeorgesStavracas** [comment] 2022-08-09 14:58
https://github.com/flatpak/xdg-desktop-portal/pull/853 exists, now someone with proper authority have to review and eventually merge that

**Closed** 2022-08-10 18:10 UTC

**Comment by axel-n** [comment] 2022-09-16 08:00
any news? please give user a chance to setup this feature

**Comment by jadahl** [comment] 2022-09-16 08:19
> any news? please give user a chance to setup this feature

This has already been added.

**Comment by axel-n** [comment] 2022-09-16 08:33
> > any news? please give user a chance to setup this feature
> 
> This has already been added.

ok, how to always add permission to share screenshots to some application?

now I can not see this option
![image](https://user-images.githubusercontent.com/6695246/190594258-7c50337b-8548-4778-99dc-dda4809f698c.png)

**Comment by michael-hart-github** [comment] 2022-09-27 21:01
@jadahl If you happen to have info on where/how we can set this, please reply. I have run into this issue recently as well, and had initially assumed there was an issue with flameshot, since I had never used it before. Realizing that this is a permissions thing, that I need to permit each time I launch the program, is getting very tedious to deal with even if the program itself is _considerably_ better than the default screenshot program.

@axel-n How did you go about getting all of those permissions listed in Settings? My own listing looks like this
![application_list](https://user-images.githubusercontent.com/5470143/192634605-c47ecbdd-10bf-40b4-8aa7-e35bfb1b66af.png)

**Comment by kon14** [comment] 2022-09-27 21:05
> @axel-n How did you go about getting all of those permissions listed in Settings? My own listing looks like this
> ![application_list](https://user-images.githubusercontent.com/5470143/192634605-c47ecbdd-10bf-40b4-8aa7-e35bfb1b66af.png)
> 

@michael-hart-github 
That's [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal), not Gnome Settings.

**Comment by michael-hart-github** [comment] 2022-09-27 21:45
> > @axel-n How did you go about getting all of those permissions listed in Settings?
> 
> @michael-hart-github That's [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal), not Gnome Settings.

@kon14
Ah, got it. Thank you!

**Comment by andreyizrailev** [comment] 2022-10-21 08:47
I'm sorry if I missed something, but I wasn't able to find any guidence on how to update xdg-desktop-portal in order for gnome not to ask if I want to share my screenshot with Flameshot every time. Could you please point me to how I can do this? I'm using ubuntu 22.04 with gnome 42.

**Comment by gpothier** [comment] 2022-10-21 13:05
@andreyizrailev I think the easiest solution would be for you to upgrade to 22.10, which has this feature out of the box. And the new Gnome in that version is quite nice too, so I'd say it's worth the upgrade.

**Comment by andreyizrailev** [comment] 2022-10-21 15:32
@gpothier that is very unfortunate that I have to choose between the long term support and a convenient way of making screenshots. But thank you for the answer!

**Comment by rainisto** [comment] 2022-10-24 16:02
btw, how fast is the portal api? Can it do 30+FPS? Currently I have X11 python application using mss.grab() which takes screenshots on desktop regions 30fps and calculates averages which controls ambient led-strip around the monitor in real time. So I would need to be able to do the same in Wayland. Or is there no way to use Wayland because of security restrictions?

**Comment by jadahl** [comment] 2022-10-24 16:06
> btw, how fast is the portal api? Can it do 30+FPS?

You shouldn't use the screenshot portal to make screencasts, there is the screenast portal for that.

**Comment by rainisto** [comment] 2022-10-24 16:18
> > btw, how fast is the portal api? Can it do 30+FPS?
> 
> You shouldn't use the screenshot portal to make screencasts, there is the screenast portal for that.

I'm currently capturing bbox regions from 4k desktop (for performance reasons). Is screencast portal able to provide casts from partial desktop regions? Have to start searching for API documentation.

**Comment by jadahl** [comment] 2022-10-24 16:43
> Is screencast portal able to provide casts from partial desktop regions?

No, but can in theory be added.

> Does screencast portal api have setting for not asking end user permissions

Yes.

**Comment by All3xJ** [comment] 2022-11-02 17:18
Thanks a lot, devs! :D expecially @GeorgesStavracas

**Comment by Pheggas** [comment] 2022-11-03 22:06
Why is this closed? The issue is still there.

**Comment by mcatanzaro** [comment] 2022-11-03 22:09
This issue was fixed by c8274173f7d127f1d7e39e8b5bcaf7f0ee751f48.

**Comment by ZaneBartlett1** [comment] 2023-04-21 17:16
For people who are a bit newer to Linux - 

Note that Ubuntu releases are the year and date, so Ubuntu 22.04 was released 2022 on the 4th month.

Ubuntu 22.04 LTS comes with GNOME 42.5 (you can verify this yourself by running `gnome-shell --version`), and it's highly unlikely to receive an official update to GNOME 43. LTS releases happen every two years, so the next one will be Ubuntu 24.04 LTS, which will include GNOME 43 or a newer version.

If you want GNOME 43 sooner, you can upgrade to Ubuntu 22.10 when it's released, but non-LTS releases have a shorter support period of 9 months. This means you'll need to upgrade more frequently to stay on a supported version.

Another option is to install GNOME 43 from a third-party repository (like a PPA) or build it from source. This method can be risky, as it might cause compatibility issues or system instability. If you choose this path, you should really consider backing up your data and be ready to troubleshoot potential issues. If you had to read this to understand the situation, I don't really suggest this option.

**Comment by lxwulf** [comment] 2024-03-21 17:45
Sorry to bother you, but I don't get why it doesn't work on my `Fedora 39` system… This should have the fix not true? I still can take screenshots with `flameshot`… :man_shrugging: :face_with_spiral_eyes: 

I appreciate every help or direction to the possible solution.

**Comment by ZaneBartlett1** [comment] 2024-03-21 18:28
@lxwulf, I don't know how you check the version of GNOME on fedora. A quick search shows that it should, but you can, and need to, directly confirm your GNOME version. If you can confirm that you're on GNOME 43+ and that there's no other changes that have been made that would cause any issues (searching error messages if you're getting them + GNOME version) then I would imagine you could treat it as a bug. I would open a new issue.

And just to be clear, you're having an issue were on Fedora 39, if you take a screenshot with flameshot, you're still being prompted on every screenshot to pass it to another program? If that's the case, then I stand by what I say above, otherwise, you may need to clarify

**Comment by whot** [comment] 2024-03-21 22:35
> I don't know how you check the version of GNOME on fedora.

fwiw, it's slightly hidden in GNOME Settings -> About -> System Details. That should work regardless of distro. Fedora is on GNOME 45.x.

**Comment by adangel** [comment] 2024-03-22 06:57
@lxwulf See https://github.com/flameshot-org/flameshot/issues/2868 - it seems, there is an issue on how flameshot is started. E.g. for me it doesn't work, if flameshot is started automatically/from the app menu. If I stop it and start it manually from _a terminal_, it works.

**Comment by lxwulf** [comment] 2024-03-25 08:03
@ZaneBartlett1:

As @whot mentioned, I'm on GNOME 45.5. It does work if I `manually` start `flameshot` from the terminal but not if it's in autostart as @adangel already mentioned. This applies for the `rpm package`, the `flatpak` version doesn't work in any case.

@adangel:

Yes, I saw this issue and also already commented. Anyway, they say the problem relies on the `xdg-desktop-portal` not on the application itself. Which it shouldn't at least not on my system because it's updated to the newest version. Do I miss a package or a setting? Is Wayland perhaps an issue?

**Comment by mcatanzaro** [comment] 2024-03-25 14:13
You probably want to create a new issue report at this point, since this one is closed.

**Comment by acosonic** [comment] 2024-12-01 17:50
Please reopen and fix the issue...

**Comment by mcatanzaro** [comment] 2024-12-01 18:35
> This issue was fixed by [c827417](https://github.com/flatpak/xdg-desktop-portal/commit/c8274173f7d127f1d7e39e8b5bcaf7f0ee751f48).

This issue was fixed two years ago. Whatever problem you're having is not this issue. Feel free to report a new issue.

**Comment by mcatanzaro** [comment] 2024-12-01 18:44
Actually, please make sure your portal backend has an access portal implementation before reporting a bug here, because the screenshot portal will always prompt you for permission if you don't have an access portal implementation. If you don't have an access portal implementation, you can report the issue to your portal backend instead. I see xdg-desktop-portal-gnome, xdg-desktop-portal-gtk, and xdg-desktop-portal-kde all have access portal implementations. But notably, xdg-desktop-portal-xapp does not. (xdg-desktop-portal-wlroots doesn't either, but that one is clearly intended to be used in combination with a more featureful portal backend, so that's probably OK.)

**Comment by nbolton** [comment] 2025-08-08 23:47
I made a program to automatically accept input capture and remote desktop permission dialogs.

https://github.com/deskflow/accept-portal-dialog

I guess I could extend this for other permission dialogs.
