### ISSUE TITLE
Unauthorized mkdir breaks Firefox Snap "Save Page As ..." feature

### ISSUE THREAD

**Issue by lissyx** [flatpak/xdg-desktop-portal#831] opened 2022-07-06 14:56 UTC
When using Firefox under a Snap, the "Save Page As ..." feature when selecting "Complete page" is broken. More context in https://bugzilla.mozilla.org/show_bug.cgi?id=1774556

From what I could diagnose:
 - Our "Save Page As ..." code will use GTK for selecting the target file
 - Then it performs download using `nsITransfer`
 - Next to the selected target file, a folder will be created to save the assets linked to the page
 
That last step fails on `mkdir` because the portal seems to deny it. Is this an actual sandbox limitation or a bug in the portal ?

If it is a limitation, are there alternatives or could we fix the sandbox to allow `mkdir` in that case ?

Attached is a small snap package reproducing the issue, via Python/DBus calls

[snap.zip](https://github.com/flatpak/xdg-desktop-portal/files/9055878/snap.zip)

**Comment by rusty-snake** [comment] 2022-07-06 15:02
Related: #463

**Comment by lissyx** [comment] 2022-07-06 16:00
> Related: #463

Looks like this exact usecase was already mentionned in https://github.com/flatpak/xdg-desktop-portal/issues/463#issuecomment-987288031.

**Comment by GeorgesStavracas** [comment] 2022-12-12 19:56
Yes. Let's keep track of this request there, and consider this a spiritual duplicate of #463.

**Closed by GeorgesStavracas** 2022-12-12 19:56 UTC
