### ISSUE TITLE
Impossible to trash a folder without following symlinks

### ISSUE THREAD

**Issue by refi64** [flatpak/xdg-desktop-portal#527] opened 2020-09-15 22:39 UTC
Observe:

```
$ mkdir -p x                                                         
$ flatpak run --command=bash -d --filesystem=home org.gnome.Sdk//3.36
[📦 org.gnome.Sdk xdg-desktop-portal]$ gjs -c 'const {Gio} = imports.gi; let file = Gio.File.new_for_path("x"); file.trash(null);'
[📦 org.gnome.Sdk xdg-desktop-portal]$ file x
x: directory
[📦 org.gnome.Sdk xdg-desktop-portal]$ 
```

Turns out, this was broken by [this GLib commit](https://gitlab.gnome.org/GNOME/glib/-/commit/c3ab139841efa0b994ccbf78fe06faf713875bc3), which uses `O_PATH | O_NOFOLLOW` to open the fd, but [the portal doesn't like that](https://github.com/flatpak/xdg-desktop-portal/blob/8fbab8933fc4e0e87dbb263c9414dc349fc3cdb8/src/xdp-utils.c#L949-L951).

However, the GLib commit really is *correct*, because without `O_NOFOLLOW`, this [will trash the targets of symlinks](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1274). Thus, from what I can tell, there is currently no way to delete a folder without following symlinks.

I'm thinking that, in this case at least, it would be okay for the portal to accept `O_PATH | O_NOFOLLOW`? At least, the logic makes sense for the trash portal, though I'm not sure about the others.

**Comment by A6GibKm** [comment] 2020-09-15 22:46
Affects https://github.com/flathub/org.gnome.baobab/issues/1.

**Comment by vdragon411** [comment] 2020-09-26 13:45
#518 related and posted some possible fixes

**Comment by GeorgesStavracas** [comment] 2023-10-06 20:45
Duplicate of https://github.com/flatpak/xdg-desktop-portal/issues/518

**Closed by GeorgesStavracas** 2023-10-06 20:45 UTC
